apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: default
  releaseName: sonarr
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 12h
  values:
    controllers:
      main:
        containers:
          main:
            env:
              PGID: 1000
              PUID: 1000
              TZ: America/Denver
            image:
              repository: ghcr.io/linuxserver/sonarr
              tag: "4.0.17"
    persistence:
      config:
        existingClaim: sonarr-config-nvmeof
      tv:
        enabled: true
        type: nfs
        server: truenas.vanwyhe.xyz
        path: /mnt/mongo/data/media/tv
        globalMounts:
          - path: /tv
      downloads:
        enabled: true
        type: nfs
        server: truenas.vanwyhe.xyz
        path: /mnt/mongo/data/torrents
    service:
      main:
        controller: main
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8989
    route:
      main:
        hostnames:
          - sonarr.int.vanwyhe.xyz
          - sonarr.i.vw4.lol
          - sonarr.int.vw4.lol
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: internal
            namespace: kube-system
            sectionName: https
