apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-nvmeof
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: org.democratic-csi.nvmeof
