apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: org.democratic-csi.iscsi
  volumeName: pvc-54cf9182-c25d-40c0-8f6d-b1112e0e466b
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-config-nvmeof
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: org.democratic-csi.nvmeof
