apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: zwavejs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zwavejs
    app.kubernetes.io/service: zwavejs
    helm.sh/chart: app-template-4.3.0
  name: zwavejs
  namespace: default
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 8091
    protocol: TCP
    targetPort: 8091
  - name: mqtt
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: zwavejs
    app.kubernetes.io/name: zwavejs
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zwavejs-config
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: org.democratic-csi.iscsi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: zwavejs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zwavejs
    helm.sh/chart: app-template-4.3.0
  name: zwavejs
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/controller: main
      app.kubernetes.io/instance: zwavejs
      app.kubernetes.io/name: zwavejs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/controller: main
        app.kubernetes.io/instance: zwavejs
        app.kubernetes.io/name: zwavejs
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: America/Denver
        - name: ZWAVEJS_EXTERNAL_CONFIG
          value: /usr/src/app/store/.config-db
        image: docker.io/kennethreitz/httpbin:latest
        name: main
        volumeMounts:
        - mountPath: /usr/src/app/store
          name: config
        - mountPath: /dev/zwave
          name: zwave
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      nodeSelector:
        attached-usb: zwave
      serviceAccountName: default
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: zwavejs-config
      - hostPath:
          path: /dev/serial/by-id/usb-Silicon_Labs_Zooz_ZST10_700_Z-Wave_Stick_0001-if00-port
          type: CharDevice
        name: zwave
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app.kubernetes.io/instance: zwavejs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zwavejs
    helm.sh/chart: app-template-4.3.0
  name: zwavejs
  namespace: default
spec:
  hostnames:
  - zwavejs.int.vanwyhe.xyz
  - zwavejs.i.vw4.lol
  - zwavejs.int.vw4.lol
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: internal
    namespace: kube-system
    sectionName: https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: zwavejs
      namespace: default
      port: 8091
      weight: 1
