apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: readmeabook-secrets
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: readmeabook-secrets
  data:
    - secretKey: config-encryption-key
      remoteRef:
        key: READMEABOOK_CONFIG_ENCRYPTION_KEY
