apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: readmeabook
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: default
  releaseName: readmeabook
  install:
    createNamespace: true
    disableWait: true
  upgrade:
    disableWait: true
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 12h
  values:
    controllers:
      main:
        containers:
          main:
            # renovate: datasource=docker depName=ghcr.io/kikootwo/readmeabook
            image:
              repository: ghcr.io/kikootwo/readmeabook
              tag: 1.1.7
            env:
              TZ: America/Denver
              PUBLIC_URL: https://bookreq.vanwyhe.xyz
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: readmeabook-database-app
                    key: uri
              REDIS_URL:
                value: redis://readmeabook-valkey:6379
              CONFIG_ENCRYPTION_KEY:
                valueFrom:
                  secretKeyRef:
                    name: readmeabook-secrets
                    key: config-encryption-key
              DISABLE_LOCAL_LOGIN: "false"
      valkey:
        containers:
          main:
            # renovate: datasource=docker depName=docker.io/valkey/valkey
            image:
              repository: docker.io/valkey/valkey
              tag: 9.0.3-alpine
    persistence:
      config:
        existingClaim: readmeabook-config
        advancedMounts:
          main:
            main:
              - path: /config
      valkey-data:
        existingClaim: readmeabook-valkey-data
        advancedMounts:
          valkey:
            main:
              - path: /data
    service:
      main:
        controller: main
        ports:
          http:
            port: 3030
      valkey:
        controller: valkey
        ports:
          redis:
            port: 6379
    route:
      main:
        hostnames:
          - bookreq.vanwyhe.xyz
          - bookreq.vw4.lol
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - group: ""
                kind: Service
                name: readmeabook-main
                namespace: default
                port: 3030
                weight: 1
