apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: overseerr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: overseerr
    app.kubernetes.io/service: overseerr
    helm.sh/chart: app-template-4.3.0
  name: overseerr
  namespace: default
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 5055
    protocol: TCP
    targetPort: 5055
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: overseerr
    app.kubernetes.io/name: overseerr
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-config
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: org.democratic-csi.iscsi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: overseerr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: overseerr
    helm.sh/chart: app-template-4.3.0
  name: overseerr
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/controller: main
      app.kubernetes.io/instance: overseerr
      app.kubernetes.io/name: overseerr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/controller: main
        app.kubernetes.io/instance: overseerr
        app.kubernetes.io/name: overseerr
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: America/Denver
        image: docker.io/kennethreitz/httpbin:latest
        name: main
        volumeMounts:
        - mountPath: /app/config
          name: config
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      serviceAccountName: default
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: overseerr-config
---
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
metadata:
  name: req-ext-dns
  namespace: default
spec:
  dnsName: k8s-req.vanwyhe.xyz
  targets:
  - home.vanwyhe.xyz
  ttl: 300
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app.kubernetes.io/instance: overseerr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: overseerr
    helm.sh/chart: app-template-4.3.0
  name: overseerr
  namespace: default
spec:
  hostnames:
  - k8s-overseerr.vanwyhe.xyz
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: external
    namespace: kube-system
    sectionName: https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: overseerr
      namespace: default
      port: 5055
      weight: 1
