allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: piraeus-storage
parameters:
  linstor.csi.linbit.com/storagePool: pool1
provisioner: linstor.csi.linbit.com
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstorcluster
spec: {}
---
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: storage-pool
spec:
  storagePools:
  - fileThinPool:
      directory: /var/piraeus-datastore/pool1
    name: pool1
