allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: piraeus-storage
parameters:
  csi.storage.k8s.io/fstype: xfs
  linstor.csi.linbit.com/storagePool: pool1
provisioner: linstor.csi.linbit.com
volumeBindingMode: WaitForFirstConsumer
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: piraeus-storage-file
parameters:
  csi.storage.k8s.io/fstype: xfs
  linstor.csi.linbit.com/storagePool: pool2
provisioner: linstor.csi.linbit.com
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstorcluster
spec: {}
---
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: storage-pool
spec:
  storagePools:
  - fileThinPool:
      directory: /var/piraeus-datastore/pool1
    name: pool1
---
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: storage-pool2
spec:
  storagePools:
  - filePool:
      directory: /var/piraeus-datastore/pool2
    name: pool2
---
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: talos-loader-override
spec:
  podTemplate:
    spec:
      initContainers:
      - $patch: delete
        name: drbd-shutdown-guard
      - $patch: delete
        name: drbd-module-loader
      volumes:
      - $patch: delete
        name: run-systemd-system
      - $patch: delete
        name: run-drbd-shutdown-guard
      - $patch: delete
        name: systemd-bus-socket
      - $patch: delete
        name: lib-modules
      - $patch: delete
        name: usr-src
      - hostPath:
          path: /var/etc/lvm/backup
          type: DirectoryOrCreate
        name: etc-lvm-backup
      - hostPath:
          path: /var/etc/lvm/archive
          type: DirectoryOrCreate
        name: etc-lvm-archive
