apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-backup-b2
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: vaultwarden-backup-b2
  data:
    - secretKey: keyId
      remoteRef:
        key: B2_KEY_ID
    - secretKey: applicationKey
      remoteRef:
        key: B2_APPLICATION_KEY
    - secretKey: bucket
      remoteRef:
        key: B2_BUCKET
