apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: vaultwarden-database
  namespace: default
spec:
  schedule: "0 0 3 * * *"
  backupOwnerReference: self
  cluster:
    name: vaultwarden-database
  method: barmanObjectStore
