[tools]
doppler = "latest"
flux2 = "latest"
gh = "latest"
"github:budimanjojo/talhelper" = "latest"
helm = "latest"
kubeconform = "latest"
kube-score = "latest"
kustomize = "latest"
talosctl = "latest"
yamlfmt = "latest"
"pipx:flux-local" = "latest"
