apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: org.democratic-csi.iscsi
  volumeName: pvc-7a76362b-dbea-4806-aeb3-20e9322c101a
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data-nvmeof
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: org.democratic-csi.nvmeof
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: org.democratic-csi.iscsi
  volumeName: pvc-3a913f4b-156c-4ac9-ac79-fdb2ca246202
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache-nvmeof
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: org.democratic-csi.nvmeof
