apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-bouncer-secret
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: crowdsec-bouncer-secret
  data:
    - secretKey: apiKey
      remoteRef:
        key: CROWDSEC_BOUNCER_API_KEY
