apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookshelf-audio-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: org.democratic-csi.iscsi
  volumeName: pvc-25911bd0-729d-4988-9e81-4bf4f24bea74
