apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookshelf-audio-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: org.democratic-csi.iscsi
