apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: cloudflare-api-token-secret
    template:
      data:
        api-token: "{{ .CLOUDFLARE_API_TOKEN }}"
  data:
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: CLOUDFLARE_API_TOKEN
