apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tuppr-talosconfig
  namespace: system-upgrade
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: tuppr-talosconfig
  data:
    - secretKey: talosconfig
      remoteRef:
        key: TALOSCONFIG
