apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-vanwyhe-xyz
  namespace: default
spec:
  secretName: wildcard-vanwyhe-xyz-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: vanwyhe.xyz
  dnsNames:
    - vanwyhe.xyz
    - "*.vanwyhe.xyz"
    - "*.int.vanwyhe.xyz"
---
# allows the kube-system gateways to use the cert secret in default
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: gateways-to-wildcard-cert
  namespace: default
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: kube-system
  to:
    - group: ""
      kind: Secret
      name: wildcard-vanwyhe-xyz-tls
