apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smokeping-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: org.democratic-csi.iscsi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smokeping-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: org.democratic-csi.iscsi
