apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pve-exporter-secrets
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: pve-exporter-secrets
  data:
    - secretKey: tokenValue
      remoteRef:
        key: PVE_EXPORTER_TOKEN_VALUE
