apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-data-nvmeof
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: org.democratic-csi.nvmeof
