apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: org.democratic-csi.iscsi
  volumeName: pvc-9d3fac21-b1d5-419c-bd11-27ada38f9c4f
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-nvmeof
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: org.democratic-csi.nvmeof
