apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-config-volsync-restic
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: radarr-config-volsync-restic
    template:
      data:
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        RESTIC_REPOSITORY: "s3:{{ .endpoint }}/{{ .bucket }}/radarr"
  data:
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: VOLSYNC_RESTIC_PASSWORD
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: BACKUP_S3_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: BACKUP_S3_SECRET_ACCESS_KEY
    - secretKey: endpoint
      remoteRef:
        key: BACKUP_S3_ENDPOINT
    - secretKey: bucket
      remoteRef:
        key: BACKUP_S3_BUCKET
