apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret-key
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: authentik-secret-key
  data:
    - secretKey: secret-key
      remoteRef:
        key: AUTHENTIK_SECRET_KEY
