apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret-key
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: authentik-secret-key
  data:
    - secretKey: secret-key
      remoteRef:
        key: AUTHENTIK_SECRET_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smtp-config-secret
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: smtp-config-secret
  data:
    - secretKey: smtp-host
      remoteRef:
        key: SMTP_HOST
    - secretKey: smtp-username
      remoteRef:
        key: SMTP_USERNAME
    - secretKey: smtp-password
      remoteRef:
        key: SMTP_PASSWORD
    - secretKey: smtp-from
      remoteRef:
        key: SMTP_FROM
