apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: recyclarr
  data:
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: RADARR_API_KEY
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: SONARR_API_KEY
