apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trek-oidc
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: trek-oidc
  data:
    - secretKey: clientSecret
      remoteRef:
        key: TREK_OIDC_CLIENT_SECRET
    - secretKey: encryptionKey
      remoteRef:
        key: TREK_ENCRYPTION_KEY
