apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp-oidc
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: headlamp-oidc
  data:
    - secretKey: clientSecret
      remoteRef:
        key: HEADLAMP_OIDC_CLIENT_SECRET
