apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-selfie-timelapse
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: immich-selfie-timelapse
  data:
    - secretKey: apiKey
      remoteRef:
        key: IMMICH_SELFIE_TIMELAPSE_API_KEY
