apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bjw-s.yaml
  - crowdsec.yaml
  - crowdsec-bouncer.yaml
  - cilium.yaml
  - democratic-csi.yaml
  - descheduler.yaml
  - envoy-gateway.yaml
  - external-secrets.yaml
  - gardener.yaml
  - grafana.yaml
  - headlamp.yaml
  - intel.yaml
  - jetstack.yaml
  - kubelet-csr-approver.yaml
  - metrics-server.yaml
  - nfd.yaml
  - authentik.yaml
  - cnpg.yaml
  - immich.yaml
  - prometheus-community.yaml
  - nvidia.yaml
