apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: opnsense
  namespace: monitoring
spec:
  staticConfigs:
    - targets:
        - 10.0.10.1:9100
      labels:
        instance: opnsense
