apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: int.vanwyhe.xyz
  namespace: kube-system
spec:
  commonName: int.vanwyhe.xyz
  dnsNames:
  - int.vanwyhe.xyz
  - '*.int.vanwyhe.xyz'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: int.vanwyhe.xyz-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vanwyhe.xyz
  namespace: kube-system
spec:
  commonName: vanwyhe.xyz
  dnsNames:
  - vanwyhe.xyz
  - '*.vanwyhe.xyz'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: vanwyhe.xyz-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external
  namespace: kube-system
spec:
  gatewayClassName: envoy
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: http
    port: 80
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: All
    name: https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - kind: Secret
        name: vanwyhe.xyz-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  namespace: kube-system
spec:
  gatewayClassName: envoy
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: http
    port: 80
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: All
    name: https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - kind: Secret
        name: int.vanwyhe.xyz-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
  namespace: kube-system
spec:
  parentRefs:
  - name: internal
    namespace: kube-system
    sectionName: http
  - name: external
    namespace: kube-system
    sectionName: http
  rules:
  - filters:
    - requestRedirect:
        scheme: https
        statusCode: 301
      type: RequestRedirect
    matches:
    - path:
        type: PathPrefix
        value: /
