apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: kube-system
  releaseName: nvidia-device-plugin
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.19.0
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: flux-system
      interval: 12h
  values:
    deviceDiscoveryStrategy: nvml
    runtimeClassName: nvidia
    nodeSelector:
      nvidia-gpu: quadro-p2000
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: nvidia-gpu
                  operator: Exists
