apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: default
  releaseName: immich
  install:
    createNamespace: true
    disableWait: true
  upgrade:
    disableWait: true
  chart:
    spec:
      # renovate: registryUrl=oci://ghcr.io/immich-app/immich-charts
      chart: immich
      version: 0.11.1
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
      interval: 12h
  values:
    controllers:
      main:
        pod:
          securityContext:
            runAsUser: 3002
            runAsGroup: 3001
            fsGroup: 3001
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              # renovate: datasource=docker depName=ghcr.io/immich-app/immich-server
              tag: v2.6.3
            env:
              REDIS_HOSTNAME: '{{ printf "%s-valkey" .Release.Name }}'
              IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'
              DB_HOSTNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: host
              DB_DATABASE_NAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: dbname
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: username
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: password
    immich:
      persistence:
        library:
          existingClaim: immich-library
    valkey:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                # renovate: datasource=docker depName=docker.io/valkey/valkey
                tag: 9.0.3-alpine
      persistence:
        data:
          type: persistentVolumeClaim
          accessMode: ReadWriteOnce
          size: 1Gi
          storageClass: org.democratic-csi.nvmeof
    server:
      enabled: true
      route:
        main:
          hostnames:
            - photos.vanwyhe.xyz
            - photos.vw4.lol
          parentRefs:
            - group: gateway.networking.k8s.io
              kind: Gateway
              name: external
              namespace: kube-system
              sectionName: https
          rules:
            - backendRefs:
                - group: ""
                  kind: Service
                  name: immich-server
                  namespace: default
                  port: 2283
                  weight: 1
              timeouts:
                request: 1h
    machine-learning:
      enabled: true
      controllers:
        main:
          pod:
            runtimeClassName: nvidia
            nodeSelector:
              nvidia-gpu: quadro-p2000
          containers:
            main:
              image:
                # renovate: datasource=docker depName=ghcr.io/immich-app/immich-machine-learning
                tag: v2.6.3-cuda
              resources:
                limits:
                  nvidia.com/gpu: 1
      persistence:
        cache:
          type: persistentVolumeClaim
          accessMode: ReadWriteOnce
          size: 10Gi
          storageClass: org.democratic-csi.nvmeof
