apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops
  prune: true
  sourceRef:
    kind: OCIRepository
    name: default
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-crds
  namespace: flux-system
spec:
  interval: 10m
  path: config/crd
  prune: true
  sourceRef:
    kind: GitRepository
    name: gateway-crds
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: piraeus-operator
  namespace: flux-system
spec:
  interval: 10m
  path: config/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: piraeus-operator
  wait: true
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-crds
  namespace: flux-system
spec:
  interval: 10m
  ref:
    tag: v1.3.0
  url: https://github.com/kubernetes-sigs/gateway-api
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: piraeus-operator
  namespace: flux-system
spec:
  interval: 10m
  ref:
    tag: v2.9.0
  url: https://github.com/piraeusdatastore/piraeus-operator
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: default
  namespace: flux-system
spec:
  interval: 1m
  ref:
    tag: main
  url: oci://ghcr.io/chadjvw/homelab/cosmere
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 10m
  ref:
    tag: v2.6.4
  url: oci://ghcr.io/fluxcd/flux-manifests
