kind: OCIRepository
metadata:
  name: default
  namespace: flux-system
spec:
  interval: 10m
  ref:
    tag: main
  url: oci://ghcr.io/chadjvw/homelab-cosmere
---
kind: OCIRepository
metadata:
  name: flux
  namespace: flux-system
spec:
  interval: 10m
  ref:
    tag: v2.6.4
  url: oci://ghcr.io/fluxcd/flux-manifests
