apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: smokeping
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: smokeping
    app.kubernetes.io/service: smokeping
    helm.sh/chart: app-template-4.2.0
  name: smokeping
  namespace: default
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: smokeping
    app.kubernetes.io/name: smokeping
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smokeping-config
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: org.democratic-csi.iscsi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smokeping-data
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: org.democratic-csi.iscsi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: smokeping
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: smokeping
    helm.sh/chart: app-template-4.2.0
  name: smokeping
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/controller: main
      app.kubernetes.io/instance: smokeping
      app.kubernetes.io/name: smokeping
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/controller: main
        app.kubernetes.io/instance: smokeping
        app.kubernetes.io/name: smokeping
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: America/Denver
        image: ghcr.io/linuxserver/smokeping:2.9.0
        name: main
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /data
          name: data
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      serviceAccountName: default
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: smokeping-config
      - name: data
        persistentVolumeClaim:
          claimName: smokeping-data
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app.kubernetes.io/instance: smokeping
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: smokeping
    helm.sh/chart: app-template-4.2.0
  name: smokeping
  namespace: default
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: internal
    namespace: kube-system
    sectionName: https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: smokeping
      namespace: default
      port: 80
      weight: 1
