apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: default
  releaseName: prowlarr
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 12h
  values:
    controllers:
      main:
        containers:
          main:
            env:
              PGID: 1000
              PUID: 1000
              TZ: America/Denver
            image:
              repository: ghcr.io/linuxserver/prowlarr
              tag: "2.3.0"
    persistence:
      config:
        existingClaim: prowlarr-config-nvmeof
    service:
      main:
        controller: main
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          http:
            port: 9696
    route:
      main:
        hostnames:
          - prowlarr.int.vanwyhe.xyz
          - prowlarr.i.vw4.lol
          - prowlarr.int.vw4.lol
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: internal
            namespace: kube-system
            sectionName: https
