apiVersion: v1
kind: ConfigMap
metadata:
  name: kanidm-config
  namespace: default
data:
  server.toml: |
    bindaddress = "[::]:8443"
    tls_chain = "/tls/tls.crt"
    tls_key = "/tls/tls.key"
    db_path = "/data/kanidm.db"
    db_fs_type = "generic"
    origin = "https://auth.int.vanwyhe.xyz"
    domain = "vanwyhe.xyz"
    role = "WriteReplica"
    log_level = "info"
