apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kanidm-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: org.democratic-csi.nvmeof
