apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-oidc
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: mealie-oidc
  data:
    - secretKey: clientSecret
      remoteRef:
        key: MEALIE_OIDC_CLIENT_SECRET
    - secretKey: clientId
      remoteRef:
        key: MEALIE_OIDC_CLIENT_ID
