apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: default
  releaseName: mealie
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 12h
  values:
    controllers:
      main:
        containers:
          main:
            env:
              PGID: 1000
              PUID: 1000
              TZ: America/Denver
              ALLOW_SIGNUP: "false"
              BASE_URL: https://noms.vanwyhe.xyz
              TOKEN_TIME: 720
              OIDC_AUTH_ENABLED: "true"
              OIDC_SIGNUP_ENABLED: "false"
              OIDC_PROVIDER_NAME: Authentik
              OIDC_USER_GROUP: users
              OIDC_ADMIN_GROUP: admin
              OIDC_CLIENT_ID:
                valueFrom:
                  secretKeyRef:
                    name: mealie-oidc
                    key: clientId
              OIDC_CONFIGURATION_URL: https://auth.vanwyhe.xyz/application/o/mealie/.well-known/openid-configuration
              # OIDC_CLIENT_SECRET:
              #   valueFrom:
              #     secretKeyRef:
              #       name: mealie-oidc
              #       key: clientSecret
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v3.15.0
    persistence:
      config:
        existingClaim: mealie-data-nvmeof
        globalMounts:
          - path: /app/data
    service:
      main:
        controller: main
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          http:
            port: 9000
    route:
      main:
        hostnames:
          - noms.vanwyhe.xyz
          - noms.vw4.lol
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: external
            namespace: kube-system
            sectionName: https
