apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: uptimekuma-oidc
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: uptimekuma-oidc
  data:
    - secretKey: client-secret
      remoteRef:
        key: UPTIMEKUMA_OIDC_CLIENT_SECRET
