apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: uptimekuma-oidc
  namespace: monitoring
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: uptimekuma
  oidc:
    provider:
      issuer: https://auth.vanwyhe.xyz/oauth2/openid/uptimekuma-gateway
      authorizationEndpoint: https://auth.vanwyhe.xyz/ui/oauth2
      tokenEndpoint: https://auth.vanwyhe.xyz/oauth2/token
    clientID: uptimekuma-gateway
    clientSecret:
      name: uptimekuma-oidc
    redirectURL: https://kuma.int.vanwyhe.xyz/oauth2/callback
    scopes:
      - profile
      - email
      - groups
