apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/service: jellyfin
    helm.sh/chart: app-template-4.3.0
  name: jellyfin
  namespace: default
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 8096
    protocol: TCP
    targetPort: 8096
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/name: jellyfin
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: org.democratic-csi.iscsi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: org.democratic-csi.iscsi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jellyfin
    helm.sh/chart: app-template-4.3.0
  name: jellyfin
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/controller: main
      app.kubernetes.io/instance: jellyfin
      app.kubernetes.io/name: jellyfin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/controller: main
        app.kubernetes.io/instance: jellyfin
        app.kubernetes.io/name: jellyfin
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: America/Denver
        image: ghcr.io/linuxserver/jellyfin:10.11.0
        name: main
        volumeMounts:
        - mountPath: /config/cache
          name: cache
        - mountPath: /config
          name: config
        - mountPath: /dev/dri
          name: dri
        - mountPath: /media/movies
          name: movies
        - mountPath: /media/music
          name: music
        - mountPath: /transcode
          name: transcode
        - mountPath: /media/tv
          name: tv
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      nodeSelector:
        intel-igpu: intel-graphics-24eu
      serviceAccountName: default
      volumes:
      - name: cache
        persistentVolumeClaim:
          claimName: jellyfin-cache
      - name: config
        persistentVolumeClaim:
          claimName: jellyfin-data
      - hostPath:
          path: /dev/dri
          type: Directory
        name: dri
      - name: movies
        nfs:
          path: /mnt/mongo/data/media/movies
          server: truenas.vanwyhe.xyz
      - name: music
        nfs:
          path: /mnt/mongo/data/media/music
          server: truenas.vanwyhe.xyz
      - emptyDir:
          medium: Memory
          sizeLimit: 4Gi
        name: transcode
      - name: tv
        nfs:
          path: /mnt/mongo/data/media/tv
          server: truenas.vanwyhe.xyz
---
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
metadata:
  name: jellyfin-ext-lol-dns
  namespace: default
spec:
  dnsName: jellyfin.vw4.lol
  targets:
  - home.vanwyhe.xyz
  ttl: 300
---
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
metadata:
  name: jellyfin-ext-xyz-dns
  namespace: default
spec:
  dnsName: jellyfin.vanwyhe.xyz
  targets:
  - home.vanwyhe.xyz
  ttl: 300
---
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
metadata:
  name: jf-ext-lol-dns
  namespace: default
spec:
  dnsName: jf.vw4.lol
  targets:
  - home.vanwyhe.xyz
  ttl: 300
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jellyfin
    helm.sh/chart: app-template-4.3.0
  name: jellyfin
  namespace: default
spec:
  hostnames:
  - jellyfin.vanwyhe.xyz
  - jellyfin.vw4.lol
  - jf.vw4.lol
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: external
    namespace: kube-system
    sectionName: https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: jellyfin
      namespace: default
      port: 8096
      weight: 1
