apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ytdl-sub-config-nvmeof
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: org.democratic-csi.nvmeof
