clusterName: cosmere
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.12.6
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.35.3
endpoint: https://10.0.10.13:6443
allowSchedulingOnMasters: true
additionalApiServerCertSans: &sans
  - 10.0.10.12
  - 10.0.10.13
  - 10.0.10.14
  - 127.0.0.1 # Kubeprism
additionalMachineCertSans: *sans
cniConfig:
  name: none
worker:
  machineSpec:
    mode: nocloud
    arch: amd64
    secureboot: false
  schematic:
    customization:
      extraKernelArgs: &kernelArgs
        - -init_on_alloc # Less security, faster puter
        - -init_on_free # Less security, faster puter
        - -selinux # Less security, faster puter
        - apparmor=0 # Less security, faster puter
        - init_on_alloc=0 # Less security, faster puter
        - init_on_free=0 # Less security, faster puter
        - intel_iommu=on # PCI Passthrough
        - iommu=pt # PCI Passthrough
        - mitigations=off # Less security, faster puter
        - security=none # Less security, faster puter
        - sysctl.kernel.kexec_load_disabled=1 # Meteor Lake CPU / iGPU
        - talos.auditd.disabled=1 # Less security, faster puter
        # https://docs.siderolabs.com/talos/v1.12/configure-your-talos-cluster/system-configuration/performance-tuning
        - cpufreq.default_governor=performance
        - intel_idle.max_cstate=0
        # https://github.com/democratic-csi/democratic-csi?tab=readme-ov-file#nvmeof
        - nvme_core.multipath=N
      systemExtensions: &extensions
        officialExtensions:
          - siderolabs/i915
          - siderolabs/intel-ucode
          - siderolabs/nvme-cli
controlPlane:
  machineSpec:
    mode: metal
    arch: amd64
    secureboot: false
  schematic:
    customization:
      extraKernelArgs: *kernelArgs
      systemExtensions: *extensions
  patches:
    - "@./patches/controlplane-talos-api-access.yaml"
    - "@./patches/controlplane-admission-control.yaml"
patches:
  - "@./patches/cluster-proxy-disabled.yaml"
  - "@./patches/containerd.yaml"
  - "@./patches/network.yaml"
  - "@./patches/features.yaml"
  - "@./patches/kubelet.yaml"
  - "@./patches/cluster-discovery.yaml"
  - "@./patches/scheduler.yaml"
  - "@./patches/sysctls.yaml"
  - "@./patches/nfs.yaml"
nodes:
  - hostname: roshar
    ipAddress: 10.0.10.13
    controlPlane: true
    installDiskSelector:
      model: INTEL*
    nodeLabels:
      # https://www.techpowerup.com/gpu-specs/hd-graphics-630.c2962
      "intel-igpu": "hd-graphics-630"
  - hostname: nalthis
    ipAddress: 10.0.10.14
    controlPlane: true
    installDiskSelector:
      busPath: /pci0000:00/0000:00:17.0/ata1/host1/target1:0:0/1:0:0:0
    nodeLabels:
      "intel-igpu": "hd-graphics-630"
      "attached-usb": "zwave"
  - hostname: scadrial
    ipAddress: 10.0.10.12
    controlPlane: true
    installDiskSelector:
      model: TWSC*
    schematic:
      customization:
        extraKernelArgs:
          - -init_on_alloc # Less security, faster puter
          - -init_on_free # Less security, faster puter
          - -selinux # Less security, faster puter
          - apparmor=0 # Less security, faster puter
          - init_on_alloc=0 # Less security, faster puter
          - init_on_free=0 # Less security, faster puter
          - intel_iommu=on # PCI Passthrough
          - iommu=pt # PCI Passthrough
          - mitigations=off # Less security, faster puter
          - security=none # Less security, faster puter
          - sysctl.kernel.kexec_load_disabled=1 # Meteor Lake CPU / iGPU
          - talos.auditd.disabled=1 # Less security, faster puter
          - i915.enable_guc=3 # Meteor Lake CPU / iGPU
          # https://docs.siderolabs.com/talos/v1.12/configure-your-talos-cluster/system-configuration/performance-tuning
          - cpufreq.default_governor=performance
          - intel_idle.max_cstate=0
          - nvme_core.multipath=N
        systemExtensions: *extensions
    nodeLabels:
      # https://www.techpowerup.com/gpu-specs/graphics-24eu-mobile.c4344
      "intel-igpu": "intel-graphics-24eu"
  - hostname: komashi
    ipAddress: 10.0.30.102
    installDiskSelector:
      model: QEMU HARDDISK
    schematic:
      customization:
        extraKernelArgs: *kernelArgs
        systemExtensions:
          officialExtensions:
            - siderolabs/i915
            - siderolabs/intel-ucode
            - siderolabs/nvme-cli
            - siderolabs/nonfree-kmod-nvidia-production
            - siderolabs/nvidia-container-toolkit-production
    patches:
      - "@./patches/komashi-nvidia-modules.yaml"
    nodeLabels:
      "nvidia-gpu": "quadro-p2000"
  - hostname: braize
    ipAddress: 10.0.30.103
    installDiskSelector:
      model: QEMU HARDDISK
  - hostname: ashyn
    ipAddress: 10.0.30.104
    installDiskSelector:
      model: QEMU HARDDISK
  - hostname: canticle
    ipAddress: 10.0.30.105
    installDiskSelector:
      model: QEMU HARDDISK
  - hostname: threnody
    ipAddress: 10.0.30.106
    installDiskSelector:
      model: QEMU HARDDISK
  - hostname: taldain
    ipAddress: 10.0.30.107
    installDiskSelector:
      model: QEMU HARDDISK
