---
clusterName: cosmere
talosVersion: v1.11.0
kubernetesVersion: v1.34.0
endpoint: https://192.168.4.107:6443
allowSchedulingOnMasters: true
additionalApiServerCertSans: &sans
  - 192.168.4.107
  - 192.168.4.119
  - 192.168.4.120
  - 127.0.0.1 # Kubeprism
additionalMachineCertSans: *sans
cniConfig:
  name: none

controlPlane:
  machineSpec: &spec
    mode: metal
    arch: amd64
    secureboot: false
  schematic:
    customization:
      extraKernelArgs:
        - -init_on_alloc # Less security, faster puter
        - -init_on_free # Less security, faster puter
        - -selinux # Less security, faster puter
        - apparmor=0 # Less security, faster puter
        - init_on_alloc=0 # Less security, faster puter
        - init_on_free=0 # Less security, faster puter
        - intel_iommu=on # PCI Passthrough
        - iommu=pt # PCI Passthrough
        - mitigations=off # Less security, faster puter
        - security=none # Less security, faster puter
        - sysctl.kernel.kexec_load_disabled=1 # Meteor Lake CPU / iGPU
        - talos.auditd.disabled=1 # Less security, faster puter
      systemExtensions:
          officialExtensions: &extensions
            - siderolabs/drbd
            - siderolabs/i915
            - siderolabs/intel-ucode
  kernelModules: &kernelMod
    - name: drbd
      parameters:
        - usermode_helper=disabled
    - name: drbd_transport_tcp
  patches:
    # Enable K8s Talos API Access
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - system-upgrade
    # Disable default API server admission plugins.
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl

worker:
  machineSpec: *spec
  kernelModules: *kernelMod
  schematic:
    customization:
      systemExtensions:
          officialExtensions: *extensions

patches:
  # disable kubeproxy for cilium
  - |-
     cluster:
       proxy:
         disabled: true

  # Configure containerd
  - |-
    machine:
      files:
        - op: create
          path: /etc/cri/conf.d/20-customization.part
          content: |
            [plugins]
              [plugins."io.containerd.grpc.v1.cri"]
                enable_unprivileged_ports = true
                enable_unprivileged_icmp = true
            [plugins."io.containerd.grpc.v1.cri".containerd]
              discard_unpacked_layers = false
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
              discard_unpacked_layers = false

  # Disable search domain everywhere
  - |-
    machine:
      network:
        disableSearchDomain: true

  # Enable Host DNS
  - |-
    machine:
      features:
        hostDNS:
          enabled: true
          resolveMemberNames: true
          forwardKubeDNSToHost: false

  # Configure kubelet
  - |-
    machine:
      kubelet:
        extraArgs:
          rotate-server-certificates: "true"
        nodeIP:
          validSubnets:
              - 192.168.4.0/24

  # Enable cluster discovery
  - |-
    cluster:
      discovery:
        enabled: true
        registries:
          kubernetes:
            disabled: true
          service:
            disabled: false

  # Configure NFS mount options
  - |
    machine:
      files:
        - op: overwrite
          path: /etc/nfsmount.conf
          permissions: 0o644
          content: |
            [ NFSMount_Global_Options ]
            nfsvers=4.2
            hard=True
            noatime=True
            nodiratime=True
            nconnect=16
  # Mount linstor file path in kubelet
  - |-
    machine:
      kubelet:
        extraMounts:
          - destination: /var/piraeus-datastore
            type: bind
            source: /var/piraeus-datastore
            options: ["bind", "rshared", "rw"]
nodes:
  - hostname: yolen
    ipAddress: 192.168.4.107
    controlPlane: true
    installDiskSelector:
      model: San*
  - hostname: roshar
    ipAddress: 192.168.4.119
    controlPlane: true
    installDiskSelector:
      model: INTEL*
  - hostname: nalthis
    ipAddress: 192.168.4.120
    controlPlane: true
    installDiskSelector:
      busPath: /pci0000:00/0000:00:17.0/ata1/host1/target1:0:0/1:0:0:0
  - hostname: scadrial 
    ipAddress: 192.168.4.113
    controlPlane: false
    installDiskSelector:
      model: TWSC*
    schematic:
      customization:
        extraKernelArgs:
          - -init_on_alloc # Less security, faster puter
          - -init_on_free # Less security, faster puter
          - -selinux # Less security, faster puter
          - apparmor=0 # Less security, faster puter
          - init_on_alloc=0 # Less security, faster puter
          - init_on_free=0 # Less security, faster puter
          - intel_iommu=on # PCI Passthrough
          - iommu=pt # PCI Passthrough
          - mitigations=off # Less security, faster puter
          - security=none # Less security, faster puter
          - sysctl.kernel.kexec_load_disabled=1 # Meteor Lake CPU / iGPU
          - talos.auditd.disabled=1 # Less security, faster puter
          - i915.enable_guc=3 # Meteor Lake CPU / iGPU

