---
clusterName: cosmere
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.11.2
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.34.1
endpoint: https://10.0.10.13:6443
allowSchedulingOnMasters: true
additionalApiServerCertSans: &sans
  - 10.0.10.12
  - 10.0.10.13
  - 10.0.10.14
  - 127.0.0.1 # Kubeprism
additionalMachineCertSans: *sans
cniConfig:
  name: none

controlPlane:
  machineSpec:
    mode: metal
    arch: amd64
    secureboot: false
  schematic:
    customization:
      extraKernelArgs:
        - -init_on_alloc # Less security, faster puter
        - -init_on_free # Less security, faster puter
        - -selinux # Less security, faster puter
        - apparmor=0 # Less security, faster puter
        - init_on_alloc=0 # Less security, faster puter
        - init_on_free=0 # Less security, faster puter
        - intel_iommu=on # PCI Passthrough
        - iommu=pt # PCI Passthrough
        - mitigations=off # Less security, faster puter
        - security=none # Less security, faster puter
        - sysctl.kernel.kexec_load_disabled=1 # Meteor Lake CPU / iGPU
        - talos.auditd.disabled=1 # Less security, faster puter
      systemExtensions: &extensions
          officialExtensions:
            - siderolabs/iscsi-tools
            - siderolabs/i915
            - siderolabs/intel-ucode
  patches:
    # Enable K8s Talos API Access
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - system-upgrade
    # Disable default API server admission plugins.
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl

patches:
  # disable kubeproxy for cilium
  - |-
     cluster:
       proxy:
         disabled: true

  # Configure containerd
  - |-
    machine:
      files:
        - op: create
          path: /etc/cri/conf.d/20-customization.part
          content: |
            [plugins]
              [plugins."io.containerd.grpc.v1.cri"]
                enable_unprivileged_ports = true
                enable_unprivileged_icmp = true
            [plugins."io.containerd.grpc.v1.cri".containerd]
              discard_unpacked_layers = false
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
              discard_unpacked_layers = false

  # Disable search domain everywhere
  - |-
    machine:
      network:
        disableSearchDomain: true

  # Enable Host DNS
  - |-
    machine:
      features:
        hostDNS:
          enabled: true
          resolveMemberNames: true
          forwardKubeDNSToHost: false

  # Configure kubelet
  - |-
    machine:
      kubelet:
        extraArgs:
          rotate-server-certificates: "true"
        nodeIP:
          validSubnets:
              - 10.0.0.0/16

  # Enable cluster discovery
  - |-
    cluster:
      discovery:
        enabled: true
        registries:
          kubernetes:
            disabled: true
          service:
            disabled: false

  # Configure NFS mount options
  - |
    machine:
      files:
        - op: overwrite
          path: /etc/nfsmount.conf
          permissions: 0o644
          content: |
            [ NFSMount_Global_Options ]
            nfsvers=4.2
            hard=True
            noatime=True
            nodiratime=True
            nconnect=16

nodes:
  - hostname: roshar
    ipAddress: 10.0.10.13
    controlPlane: true
    installDiskSelector:
      model: INTEL*
    nodeLabels:
      # https://www.techpowerup.com/gpu-specs/hd-graphics-630.c2962
      "intel-igpu": "hd-graphics-630"
  - hostname: nalthis
    ipAddress: 10.0.10.14
    controlPlane: true
    installDiskSelector:
      busPath: /pci0000:00/0000:00:17.0/ata1/host1/target1:0:0/1:0:0:0
    nodeLabels:
      "intel-igpu": "hd-graphics-630"
      "attached-usb": "zwave"
  - hostname: scadrial 
    ipAddress: 10.0.10.12
    controlPlane: true
    installDiskSelector:
      model: TWSC*
    schematic:
      customization:
        extraKernelArgs:
          - -init_on_alloc # Less security, faster puter
          - -init_on_free # Less security, faster puter
          - -selinux # Less security, faster puter
          - apparmor=0 # Less security, faster puter
          - init_on_alloc=0 # Less security, faster puter
          - init_on_free=0 # Less security, faster puter
          - intel_iommu=on # PCI Passthrough
          - iommu=pt # PCI Passthrough
          - mitigations=off # Less security, faster puter
          - security=none # Less security, faster puter
          - sysctl.kernel.kexec_load_disabled=1 # Meteor Lake CPU / iGPU
          - talos.auditd.disabled=1 # Less security, faster puter
          - i915.enable_guc=3 # Meteor Lake CPU / iGPU
        systemExtensions: *extensions
    nodeLabels:
      # https://www.techpowerup.com/gpu-specs/graphics-24eu-mobile.c4344
      "intel-igpu": "intel-graphics-24eu"