apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
metadata:
  name: wildcard-vanwyhe-xyz-dns
  namespace: default
spec:
  dnsName: "*.vanwyhe.xyz"
  ttl: 300
  targets:
    - home.vanwyhe.xyz
---
apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
metadata:
  name: wildcard-vw4-lol-dns
  namespace: default
spec:
  dnsName: "*.vw4.lol"
  ttl: 300
  targets:
    - home.vanwyhe.xyz
