apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-secrets
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: crowdsec-secrets
  data:
    - secretKey: enrollKey
      remoteRef:
        key: CROWDSEC_ENROLL_KEY
    - secretKey: registrationToken
      remoteRef:
        key: CROWDSEC_REGISTRATION_TOKEN
    - secretKey: envoyBouncerKey
      remoteRef:
        key: CROWDSEC_BOUNCER_API_KEY
    - secretKey: opnsenseBouncerKey
      remoteRef:
        key: CROWDSEC_OPNSENSE_BOUNCER_KEY
    - secretKey: csLapiSecret
      remoteRef:
        key: CROWDSEC_LAPI_SECRET
