apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-secrets
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: crowdsec-secrets
  data:
    - secretKey: enrollKey
      remoteRef:
        key: CROWDSEC_ENROLL_KEY
