apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crowdsec
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: security
  releaseName: crowdsec
  install:
    createNamespace: true
  chart:
    spec:
      chart: crowdsec
      version: "0.23.0"
      sourceRef:
        kind: HelmRepository
        name: crowdsec
        namespace: flux-system
      interval: 12h
  values:
    container_runtime: containerd
    secrets:
      externalSecret:
        name: crowdsec-secrets
        registrationTokenKey: registrationToken
        csLapiSecretKey: csLapiSecret
    config:
      config.yaml.local: |
        db_config:
          use_wal: true
          flush:
            agents_autodelete:
              cert: 60m
              login_password: 60m
        api:
          server:
            auto_registration:
              enabled: true
              token: "${REGISTRATION_TOKEN}"
              allowed_ranges:
                - 127.0.0.1/32
                - 10.0.10.0/24   # nodes, opnsense, local devices
                - 10.0.30.0/24   # proxmox / VMs
                - 10.0.40.0/24   # load balancer pool
                - 10.244.0.0/16  # pods
                - 10.96.0.0/12   # services
      profiles.yaml: |
        name: appsec_ip_remediation
        filters:
          - Alert.GetScope() == "Ip" && (Alert.GetScenario() contains "appsec" || Alert.GetScenario() contains "vpatch" || Alert.GetScenario() contains "generic-")
        decisions:
          - type: ban
            duration: 4h
        on_success: break
        ---
        name: default_ip_remediation
        filters:
          - Alert.Remediation == true && Alert.GetScope() == "Ip"
        decisions:
          - type: ban
            duration: 4h
        on_success: break
        ---
        name: default_range_remediation
        filters:
          - Alert.Remediation == true && Alert.GetScope() == "Range"
        decisions:
          - type: ban
            duration: 4h
        on_success: break
    agent:
      isDeployment: false
      acquisition:
        - namespace: default
          podName: authentik-server-*
          program: authentik
          poll_without_inotify: true
        - namespace: kube-system
          podName: envoy-kube-system-*
          program: envoy-gateway
          poll_without_inotify: true
      env:
        - name: COLLECTIONS
          value: "crowdsecurity/base-http-scenarios crowdsecurity/http-dos crowdsecurity/http-cve crowdsecurity/appsec-generic-rules crowdsecurity/appsec-virtual-patching crowdsecurity/linux firix/authentik yanis-kouidri/envoy"
        - name: PARSERS
          value: "crowdsecurity/http-logs crowdsecurity/cri-logs"
          # metrics:
          #   enabled: true
          #   serviceMonitor:
          #     enabled: true
          #     additionalLabels:
          #       release: kube-prometheus-stack
    lapi:
      persistentVolume:
        data:
          storageClassName: org.democratic-csi.nvmeof
        config:
          storageClassName: org.democratic-csi.nvmeof
          size: 512Mi
      env:
        - name: ENROLL_KEY
          valueFrom:
            secretKeyRef:
              name: crowdsec-secrets
              key: enrollKey
        - name: ENROLL_INSTANCE_NAME
          value: "cosmere"
        - name: ENROLL_TAGS
          value: "k8s talos"
        - name: BOUNCER_KEY_opnsense
          valueFrom:
            secretKeyRef:
              name: crowdsec-secrets
              key: opnsenseBouncerKey
              # metrics:
              #   enabled: true
              #   serviceMonitor:
              #     enabled: true
              #     additionalLabels:
              #       release: kube-prometheus-stack
    appsec:
      enabled: true
      env:
        - name: COLLECTIONS
          value: "crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules"
      acquisitions:
        - source: appsec
          listen_addr: "0.0.0.0:7422"
          appsec_configs:
            - crowdsecurity/appsec-default
          labels:
            type: appsec
      # metrics:
      #   enabled: true
      #   serviceMonitor:
      #     enabled: true
      #     additionalLabels:
      #       release: kube-prometheus-stack
