apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-oidc
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: home-assistant-oidc
  data:
    - secretKey: client-secret
      remoteRef:
        key: HA_OIDC_CLIENT_SECRET
