apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: default
  releaseName: home-assistant
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 12h
  values:
    controllers:
      main:
        containers:
          main:
            # renovate: datasource=docker depName=ghcr.io/home-assistant/home-assistant
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: "2025.4.4"
            env:
              PGID: 1000
              PUID: 1000
              TZ: America/Denver
            securityContext:
              privileged: true
    persistence:
      config:
        existingClaim: home-assistant-config-nvmeof
    service:
      main:
        controller: main
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8123
    route:
      main:
        hostnames:
          - home-assistant.int.vanwyhe.xyz
          - home-assistant.i.vw4.lol
          - home-assistant.int.vw4.lol
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: external
            namespace: kube-system
            sectionName: https
