apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: audiobookshelf
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: default
  releaseName: audiobookshelf
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 12h
  values:
    controllers:
      main:
        containers:
          main:
            env:
              PGID: 1000
              PUID: 1000
              TZ: America/Denver
            image:
              repository: ghcr.io/advplyr/audiobookshelf
              tag: "2.33.1"
    persistence:
      config:
        existingClaim: audiobookshelf-config-nvmeof
      metadata:
        existingClaim: audiobookshelf-metadata-nvmeof
      audiobooks:
        enabled: true
        type: nfs
        server: truenas.vanwyhe.xyz
        path: /mnt/mongo/data/media/books
    service:
      main:
        controller: main
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          http:
            port: 80
    route:
      main:
        hostnames:
          - books.vanwyhe.xyz
          - books.vw4.lol
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - group: ""
                kind: Service
                name: audiobookshelf
                namespace: default
                port: 80
                weight: 1
            timeouts:
              request: 1h
