apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config-nvmeof
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: org.democratic-csi.nvmeof
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-metadata-nvmeof
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: org.democratic-csi.nvmeof
