apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dawarich-secrets
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: dawarich-secrets
  data:
    - secretKey: secret-key-base
      remoteRef:
        key: DAWARICH_SECRET_KEY_BASE
    - secretKey: oidc-client-secret
      remoteRef:
        key: DAWARICH_OIDC_CLIENT_SECRET
