apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - cnpg-cluster.yaml
  - cnpg-scheduledbackup.yaml
  - pvc.yaml
  - externalsecret.yaml
  - servicemonitor.yaml
  - grafana-dashboard.yaml
  - volsync-restic-externalsecret.yaml
  - volsync-replicationsource.yaml
