apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dawarich-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: org.democratic-csi.nvmeof
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dawarich-valkey-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: org.democratic-csi.nvmeof
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dawarich-photon-data
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: truenas.vanwyhe.xyz
    path: /mnt/mongo/data/dawarich-photon
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dawarich-photon-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: ""
  volumeName: dawarich-photon-data
