apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubelet-csr-approver
  namespace: flux-system
spec:
  interval: 1h
  path: ./infra/kubelet-csr-approver
  prune: true
  sourceRef:
    kind: OCIRepository
    name: default
  dependsOn:
    - name: repos
