apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
  namespace: default
spec:
  instances: 1
  # renovate: datasource=docker depName=ghcr.io/tensorchord/cloudnative-vectorchord
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3
  storage:
    size: 5Gi
    storageClass: org.democratic-csi.nvmeof
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  bootstrap:
    initdb:
      postInitApplicationSQL:
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;
