apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: generic-device-plugin
    namespace: flux-system
spec:
    force: true
    interval: 1m
    path: components/generic-device-plugin
    prune: true
    sourceRef:
        kind: OCIRepository
        name: default
    targetNamespace: kube-system
