apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: intel-device-plugins-gpu
    namespace: flux-system
spec:
    force: true
    interval: 1m
    path: components/intel-device-plugins-gpu
    prune: true
    sourceRef:
        kind: OCIRepository
        name: default
    targetNamespace: node-feature-discovery
