apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: kgateway-crds
    namespace: flux-system
spec:
    force: true
    interval: 1m
    path: components/kgateway-crds
    prune: true
    sourceRef:
        kind: OCIRepository
        name: default
    targetNamespace: kgateway-system
