apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: podinfo
    namespace: flux-system
spec:
    force: true
    interval: 5m
    path: deploy/components/podinfo
    prune: true
    sourceRef:
        kind: OCIRepository
        name: default
