apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: truenas-nvmeof-driver-config
  namespace: storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: truenas-nvmeof-driver-config
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |
          driver: freenas-api-nvmeof
          instance_id: null
          httpConnection:
            protocol: http
            host: "{{ .TRUENAS_IP }}"
            port: 80
            apiKey: "{{ .TRUENAS_API_KEY }}"
            allowInsecure: true
          zfs:
            datasetParentName: mongo/k8s/nvmeof/v
            detachedSnapshotsDatasetParentName: mongo/k8s/nvmeof/s
            datasetProperties:
              "org.freenas:description": "{{ `{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}` }}"
            zvolEnableReservation: false
          nvmeof:
            transports:
              - tcp://{{ .TRUENAS_IP }}:4420
            namePrefix: csi-
            nameSuffix: -cosmere
            ports:
              - 1
            subsystemTemplate:
              pi_enable: true
              qid_max:
              ieee_oui:
              ana:
  data:
    - secretKey: TRUENAS_IP
      remoteRef:
        key: TRUENAS_IP
    - secretKey: TRUENAS_API_KEY
      remoteRef:
        key: TRUENAS_API_KEY
