name: Publish as OCI
on:
  workflow_run:
    workflows: ["Validate"]
    types: [completed]
    branches: [main]
  workflow_dispatch:
permissions:
  packages: write
  contents: read
  id-token: write
env:
  OCI_REPO: "oci://ghcr.io/chadjvw/homelab/cosmere"
jobs:
  push-artifact:
    if: github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push')
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@f05a280b876a3a1d35a76a91f701e605777853aa # v2.9.1
      - name: Install cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push artifact
        run: |
          digest="$(flux push artifact $OCI_REPO:main \
            --path="./" \
            --source="$(git config --get remote.origin.url)" \
            --revision="$(git branch --show-current)@sha1:$(git rev-parse HEAD)" \
            --output json | jq -r '.digest')"
          echo "ARTIFACT_DIGEST=${OCI_REPO#oci://}@${digest}" >> "$GITHUB_ENV"
      - name: Sign artifact
        run: cosign sign --yes "$ARTIFACT_DIGEST"
